## slm-run --load data/courses.ttl --config config.bok --format=turtle -f queries/bok.sparql --debug
PREFIX ns1: <http://example.org/course/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.org/>

SELECT DISTINCT ?s ?label ?ku_source ?score ?parcours ?ka ?ku ?llm WHERE {
    ?s ns1:content ?content .
    ?s rdfs:label ?label .
    ?s ns1:objective ?objective .
    ?s ns1:parcours ?parcours .
    FILTER(CONTAINS(?parcours, "ALMA"))
    BIND(CONCAT("Label: ",STR(?label)," Objectif: ",STR(?objective),
                " Course content: ", STR(?content)," Course name: ",STR(?s)) AS ?UE)
    BIND(ex:SLM-SEARCH-FAISS(?UE,?s,3) AS ?retrieval_graph)
    GRAPH ?retrieval_graph {
        ?s ex:is_aligned_with ?bn .
        ?bn ex:has_score ?score .
        ?bn ex:has_source ?ku_source .
        ?bn ex:has_chunk ?chunk .
    }
#    OPTIONAL {
#        FILTER(xsd:float(?score) < 0.7)
        BIND (REPLACE(str(?ku_source), "file://.*/([^/]+)/[^/]+\\.txt$", "$1") AS ?ka) 
        BIND (REPLACE(str(?ku_source), "file://.*/([^/]+)/([^/]+)\\.txt$", "$2") AS ?ku)
        BIND(ex:SLM-READFILE(?ku_source) AS ?ku_content)

        BIND(CONCAT("""
            This first page describe the content of a lecture,
            the second page describe the content of a Knowledge Unit in Computer Science:
            <page1>""",STR(?UE), " </page1> <page2> ",STR(?ku_content),
            "</page2> Does the lecture cover a large subset of the knowledge Unit. Answer in the following format:",
            "Yes/No ") AS ?prompt)
        BIND(ex:SLM-LLM(?prompt) AS ?llm)
#    }
} 