## slm-run --config config.bok  -f queries/master_stat.sparql 
PREFIX ex: <http://example.org/>

SELECT DISTINCT ?s 
WHERE {
    BIND(ex:SLM-FILE("./data/courses.ttl") AS ?input)
    BIND(ex:SLM-RDF(?input,"turtle") AS ?ginput)
    graph ?ginput {
        ?s ?p ?o .
    }
}
