## slm-run  --config config.bok  -f queries/bok-graph.sparql --debug
PREFIX ns1: <http://example.org/course/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex: <http://example.org/>
PREFIX align: <http://align.org/>

SELECT DISTINCT ?course  ?score ?ku ?ka ?answer ?explain 
WHERE {
    BIND(ex:SLM-FILE("data/exam2desc.ttl") AS ?input)
    BIND(ex:SLM-RDF(?input,"turtle") AS ?ginput)
    graph ?ginput { 
        { 
            SELECT ?course ( group_concat(?objective) as ?objectives) 
                ( group_concat(?content) as ?contents)
                ( group_concat(?topic) as ?topics)
            WHERE {
                ?course ns1:description ?content .
                ?course ns1:hasObjective ?objective .
                ?course ns1:hasTopic ?topic .
            } group by ?s limit 1 offset {OFFSET}
        }           
       }
    BIND(CONCAT(" Objective: ",STR(?objectives),
                " Course content: ", STR(?contents)," Course topic: ",STR(?topics)) AS ?course_desc)
    BIND(ex:SLM-SEARCH-FAISS(?course_desc,?course,3) AS ?search_graph)
    GRAPH ?search_graph {
        ?course ex:is_aligned_with ?bn .
        ?bn ex:has_score ?score .
        ?bn ex:has_source ?ku_source .
        ?bn ex:has_chunk ?chunk .
    }
    BIND (REPLACE(str(?ku_source), "file://.*/([^/]+)/[^/]+\\.txt$", "$1") AS ?ka) 
    BIND (REPLACE(str(?ku_source), "file://.*/([^/]+)/([^/]+)\\.txt$", "$2") AS ?ku)
    BIND(ex:SLM-READFILE(?ku_source) AS ?ku_content)

    BIND(CONCAT("""
        This first page describes the content of a course,
        the second page describes the content of a Knowledge Unit in Computer Science:
        <page1>""",STR(?course_desc), " </page1> <page2> ",STR(?ku_content),
        """</page2> 
        Does the course cover a large subset of the knowledge Unit. Answer in JSN-LD only with a type  Report",
                "@context": "https://schema.org/",
                "@type": "Report",
                "http://schema.org/answer": "A",
                "http://schema.org/explain": "B",
        Replace A by 0 it does not cover, 1 if it cover.
        Replace B by a very short explanation""") AS ?prompt)
    BIND(ex:SLM-LLMGRAPH(?prompt,?course) AS ?llm_graph)
    GRAPH ?llm_graph {
        ?course ex:has_schema_type ?root .
        ?root a <http://schema.org/Report>  .
        ?root <http://schema.org/answer> ?answer .
        ?root <http://schema.org/explain> ?explain .    
    }
} 